language: c
compiler:
  - gcc
env:
  global:
    # Your normal Travis CI build command
    # Normally this would be in the script: tag of .travis.yml, instead place it here
    - STANDARD_BUILD_COMMAND="gcc HelloWorld.c"

    # -- BEGIN Coverity Scan ENV

    # Pre-configuration steps that should not be analyzed
    # i.e. "./configure"
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND=""

   
script: gcc HelloWorld.c
