language: c
compiler:
  - gcc

env:
  global:
    # Move the command from your script: section here
    - STANDARD_BUILD_COMMAND="gcc HelloWorld.c"

    # -- BEGIN Coverity Scan ENV

    # ---- BEGIN Project-specific configuration

    - PROJECT_NAME="daksheshvyas/MyHelloWorld"

    # Email address for notifications related to this build
    - OWNER_EMAIL="daksheshvyas@yahoo.com"

    # Regular expression selects on which branches to run analysis
    # Be aware of quotas. Do not run on every branch/commit
    - COVERITY_SCAN_BRANCH_PATTERN="master"

    # Optionally execute a command immediately before cov-build,
    #   pre-configuration required for the COVERITY_SCAN_BUILD_COMMAND
    #   i.e. "./configure"
    - COVERITY_SCAN_BUILD_COMMAND_PREPEND=""

    # Insert the cov-build build commmand here
    - COVERITY_SCAN_BUILD_COMMAND="gcc HelloWorld.c"

    # COVERITY_SCAN_TOKEN via "travis encrypt" using the repo's public key
    - secure: "WzU4eyIK6dD08FwqgtnV5YFF3379jlDVozXUNADEJ1kkzgDvMeO7fR4LY1ZRo8unNX/ZXoX0t9Ou0byvKmPIZRcMkY0s60ITjMUxauYpCR1i1QMnVHr1zlOj/jdnavikhiZy6CVT/FbF1IDfTNV/gjzJQFHNxhIZyvvVlOvuODs="
    # ---- END Project-specific configuration

    #- COVERITY_SCAN_BUILD_URL="http://scan.coverity.com/scripts/travisci_build_coverity_scan.sh"
    - COVERITY_SCAN_BUILD_URL="https://gist.github.com/aceofspades/4bd0dd25f2cbfde5093c/raw"
    - COVERITY_SCAN_BUILD="curl -s $COVERITY_SCAN_BUILD_URL | bash"

    # -- END Coverity Scan ENV

  # Note: Your build matrix configuration may vary
  # Consult Travis CI Docs for more information
  # http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix
  matrix:
    - COVERITY_SCAN=0
    - COVERITY_SCAN=1

script:
  # Move your original script to STANDARD_BUILD_COMMAND
  - if [ "${COVERITY_SCAN}" = '1' ]; then eval "$COVERITY_SCAN_BUILD"; else eval "$STANDARD_BUILD_COMMAND"; fi

